// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:37814771-5fca-4437-9338-b16813dd1b2a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_H8LErxkpN",
    "aws_user_pools_web_client_id": "10eavoe3ufj2d70m5m3m2hl4pl"
};


export default awsmobile;
